"""token username

Revision ID: 110ca1cce93e
Revises: 7e458ded911e
Create Date: 2021-03-28 17:55:45.863198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110ca1cce93e'
down_revision = '7e458ded911e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('username', sa.String(), nullable=True))
    op.create_foreign_key(None, 'token', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_column('token', 'username')
    # ### end Alembic commands ###
