"""user enrolled

Revision ID: 143af3ba597c
Revises: 6c031ddd93d7
Create Date: 2021-02-21 14:24:18.662479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '143af3ba597c'
down_revision = '6c031ddd93d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classrooms', 'enrolled')
    op.add_column('user', sa.Column('enrolled', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'enrolled')
    op.add_column('classrooms', sa.Column('enrolled', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
