"""classroom array

Revision ID: 5d953667c17f
Revises: 32c35ee74c52
Create Date: 2021-02-20 12:18:53.961703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d953667c17f'
down_revision = '32c35ee74c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('enrolled', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classrooms', 'enrolled')
    # ### end Alembic commands ###
