"""classroom array

Revision ID: 6c031ddd93d7
Revises: 5d953667c17f
Create Date: 2021-02-20 12:19:23.012517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c031ddd93d7'
down_revision = '5d953667c17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
