"""entry code

Revision ID: 82acb540f1ca
Revises: f3d55ea64d82
Create Date: 2021-03-05 18:27:24.398914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82acb540f1ca'
down_revision = 'f3d55ea64d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('entry_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classrooms', 'entry_code')
    # ### end Alembic commands ###
